/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiGenerateScriptRouteImport } from './routes/api/generate-script'
import { Route as ApiGenerateVoiceRouteImport } from './routes/api/generate-voice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateScriptRoute = ApiGenerateScriptRouteImport.update({
  id: '/api/generate-script',
  path: '/api/generate-script',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateVoiceRoute = ApiGenerateVoiceRouteImport.update({
  id: '/api/generate-voice',
  path: '/api/generate-voice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/generate-script': typeof ApiGenerateScriptRoute
  '/api/generate-voice': typeof ApiGenerateVoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/generate-script': typeof ApiGenerateScriptRoute
  '/api/generate-voice': typeof ApiGenerateVoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/generate-script': typeof ApiGenerateScriptRoute
  '/api/generate-voice': typeof ApiGenerateVoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api/generate-image' | '/api/generate-script' | '/api/generate-voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/api/generate-image' | '/api/generate-script' | '/api/generate-voice'
  id:
    | '__root__'
    | '/'
    | '/api/generate-image'
    | '/api/generate-script'
    | '/api/generate-voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiGenerateScriptRoute: typeof ApiGenerateScriptRoute
  ApiGenerateVoiceRoute: typeof ApiGenerateVoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-script': {
      id: '/api/generate-script'
      path: '/api/generate-script'
      fullPath: '/api/generate-script'
      preLoaderRoute: typeof ApiGenerateScriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-voice': {
      id: '/api/generate-voice'
      path: '/api/generate-voice'
      fullPath: '/api/generate-voice'
      preLoaderRoute: typeof ApiGenerateVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiGenerateScriptRoute: ApiGenerateScriptRoute,
  ApiGenerateVoiceRoute: ApiGenerateVoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
